### ISSUE TITLE
TestRunStartedEvent properties

### ISSUE THREAD

**Issue by matepek** [hbenl/vscode-test-adapter-api#1]
Hi.
Its more like a question and a bit of a feedback:
`testStates` definition and documentation isn't consequent because `TestRunStartedEvent ` has  `tests` property too.
Please refresh the documentation, I'm not sure how many `TestRunStartedEvent` events should i send.

version 1.0.0

**Comment by hbenl** [comment]
Actually you've made me realize there's a bug there - the `tests` property in the `TestRunStartedEvent` should contain the value of the `tests` argument of the `run(tests)` method call that started the test run, so it should be `tests: string[]`.
Plus, the documentation should contain the `tests` property.
I'll fix it straight away.

**Comment by hbenl** [comment]
Fixed in version 1.0.1.
Is the documentation clear enough now?

**Comment by matepek** [comment]
Yes, TY.
