### ISSUE TITLE
TestRunFInishedEvent does not change stop icon to play after second iteration

### ISSUE THREAD

**Issue by infoneershalin** [hbenl/vscode-test-adapter-api#5]
Hi,

I am making below call to make testrun finish event after test execution or in cancel().

this.testStatesEmitter.fire(<TestRunFinishedEvent>{ type: 'finished' });

First time when I run entire suite(root), the play icon changes to stop(red coloured) and then again to play icon once execution finishes or cancelled.

But, if I execute suite(root) multiple times, then from second time the icon gets stuck in stop(red coloured) and hence I am not able to execute entire suite third time.

I am using

` 
"vscode-test-adapter-api": "^1.5.0",
"vscode-test-adapter-util": "^0.6.3",
`

 Do I need to make any extra emit call for marking finish of testrun properly?

**Comment by hbenl** [comment]
It sounds like you're doing everything right. I guess that under some circumstances an event is not sent or sent twice (e.g. if you send the `{ type: 'finished' }` event in `cancel()` and then send it again as a reaction to the child process exiting).

**Comment by infoneershalin** [comment]
You are right @hbenl.

I was calling this.testStatesEmitter.fire({ type: 'finished' }); multiple times which was setting runningCount to negative values and then it was never going in condition where you have checked (this.runningCount===0) and hence it was not setting context value.

Thanks for your reply.
