### ISSUE TITLE
New properties to TestEvent and TestDecoration

### ISSUE THREAD

**Issue by matepek** [hbenl/vscode-test-adapter-api#7]
Hello,

The following properties would be useful for some cases:

`TestEvent: filename` and `TestEvent: line`: I'm working on supporting a new framework and this stupid one does not emit this info at test-listing stage. (I know I could ask for this feature there, but because of backward compatibility I would support it in this way.)

`TestDecorator: filename`: In case of C++ it can be different from the test's filename(#incude)

**Comment by hbenl** [comment]
I have added the properties to version 1.8.0 of the API.
Version 2.16.0 of the Test Explorer contains initial support for the `TestEvent#file` and `TestEvent#line` (as well as `TestSuiteEvent#file` and `TestSuiteEvent#line`) properties, but it's still buggy: the gutter decorations do not always show up in the right place when these properties are used.
Fixing the bug (as well as the support for `TestDecoration#file`) will require some refactoring, so this may still take some time.

**Comment by matepek** [comment]
Thanks. I guess you didn't close the issue because it is still "buggy"?
It seems working nicely. Close this anytime you think.
