### ISSUE TITLE
Multi-Root Workspace support?

### ISSUE THREAD

**Issue by rossknudsen** [hbenl/vscode-test-adapter-api#8]
Just wondering if there is already, or expected to be, support for the [Multi-root Workspace API](https://github.com/Microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs) in vscode?  Or if the nature of the API requires implementation by the extension developer(s)?

**Comment by hbenl** [comment]
The Test Explorer leaves this entirely to the Test Adapter extensions. If you use [this](https://github.com/hbenl/vscode-test-adapter-api#registering-your-test-adapter-with-the-test-explorer) to register your adapter, it will automatically be instantiated once for each workspace folder, but you could also instantiate and register it only once for a workspace, even if the workspace has many folders. The idea is that test adapter developers can choose themselves how to deal with multi-root workspaces.

**Comment by rossknudsen** [comment]
Thanks so much for the reply.  Reading your documentation more carefully, it clearly explains the support for multiple workspace folders.  And I already have that code in place, so I'm golden.

Thanks again for a great extension.

**Comment by hbenl** [comment]
@rossknudsen Nice to see that someone is working on the Jest adapter again. Tell me when you're publishing to the Marketplace so I can update the link in the Test Explorer's description.

**Comment by rossknudsen** [comment]
Hey @hbenl,  I've just released to the marketplace in Preview mode.  The extension ID is `kavod-io.vscode-jest-test-adapter`.  GitHub repo [here](https://github.com/kavod-io/vscode-jest-test-adapter).

Thanks again for providing the awesome test extension.

**Comment by hbenl** [comment]
@rossknudsen Awesome! A lot of people were waiting for this since the original Jest Test Explorer was removed from the marketplace.

**Comment by rossknudsen** [comment]
Yeah, I hadn't realised that it had been removed.  I had previously attempted to contact the original author, but hadn't heard from him.  I would have thought he would be the only one that could remove it from the marketplace.
